name = "HighestDensityRegions"
uuid = "ac8b01d9-0237-5573-85ad-ea456511aa8e"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.2.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
ArgCheck = "1, 2.1"
DocStringExtensions = "0.8"
julia = "1"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Distributions", "Test"]
